[package]
name = "rust-macios-app-kit-proc-macros"
version = "0.2.2"
edition = "2021"
description = "Macros for Appkit for use in Rust-MaciOS library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.103", features = ["full"] }
quote = "1.0.0"
proc-macro2 = "1.0.0"
