[package]
name = "app-kit-proc-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.96", features = ["extra-traits"] }
quote = "1.0.18"
proc-macro2 = "1.0.39"
r3bl_rs_utils = "0.7.38"