[package]
name = "rust-macios"
version = "0.2.3"
edition = "2021"
authors = ["Allister Isaiah Harvey <a.i.harvey@icloud.com>"]
description = "Apple Frameworks for Rust"
license = "MIT"
repository = "https://github.com/a-isaiahharvey/rust-macios"

[workspace]
members = ["src/appkit/proc-macros", "src/objective_c_runtime/proc-macros"]

[profile.release]
opt-level = 0
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[features]
default = [
    "appkit",
    "background_tasks",
    "compression",
    "contacts",
    "core_foundation",
    "core_graphics",
    "core_ml",
    "foundation",
    "kernel",
    "natural_language",
    "objective_c_runtime",
    "uikit",
    "user_notifications",
]
appkit = ["objective_c_runtime"]
background_tasks = ["foundation"]
compression = []
contacts = ["foundation"]
core_foundation = ["kernel"]
core_graphics = []
core_ml = ["foundation"]
foundation = [
    "objective_c_runtime",
    "core_foundation",
    "core_graphics",
    "kernel",
]
kernel = []
natural_language = ["foundation", "core_ml"]
objective_c_runtime = ["foundation"]
uikit = ["foundation"]
user_notifications = ["foundation"]

[dependencies]
# Macros defined in workspace
app-kit-proc-macros = { version = "0.2.2", path = "src/appkit/proc-macros" }
objective-c-runtime-proc-macros = { version = "0.2.2", path = "src/objective_c_runtime/proc-macros" }

# crates.io dependencies
objc = { version = "0.2.7", features = ["exception"] }
objc_id = "0.1.1"
libc = "0.2.132"
block = "0.1.6"
lazy_static = "1.4.0"
bitflags = "1.3.2"

[dev-dependencies]
test-case = "2.1.0"

[[example]]
name = "app_delegate"
path = "examples/appkit/app_delegate.rs"

[[example]]
name = "hello_world_window"
path = "examples/appkit/hello_world_window.rs"

[[example]]
name = "popover"
path = "examples/appkit/popover.rs"

[[example]]
name = "process_info"
path = "examples/foundation/process_info.rs"

[[example]]
name = "create_contact"
path = "examples/contacts/create_contact.rs"

[[example]]
name = "general_file_decompression"
path = "examples/compression/general_file_decompression.rs"

[[example]]
name = "identifying_parts_of_speech"
path = "examples/natural_language/identifying_parts_of_speech.rs"

[[example]]
name = "identifying_people_places_and_organizations"
path = "examples/natural_language/identifying_people_places_and_organizations.rs"

[[example]]
name = "identifying_the_language_in_text"
path = "examples/natural_language/identifying_the_language_in_text.rs"

[[example]]
name = "finding_similarities_between_pieces_of_text"
path = "examples/natural_language/finding_similarities_between_pieces_of_text.rs"

[[example]]
name = "tokenizing_natural_language_text"
path = "examples/natural_language/tokenizing_natural_language_text.rs"
