[package]
name = "rust-macios"
version = "0.1.0"
edition = "2021"
authors = ["Allister Isaiah Harvey <a.i.harvey@icloud.com>"]
description = "Apple Frameworks for Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objc = { version = "0.2.7", features = ["exception"] }
objc_id = "0.1.1"
libc = "0.2.126"
block = "0.1.6"

[dev-dependencies]
test-case = "2.0.2"
